

import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import EquationContextProvider from "./context/EquationContext";
import { ThemeProvider } from "next-themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      
      <body>
      <EquationContextProvider>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        
        <NavBar></NavBar>
        {children}
        </ThemeProvider>
        </EquationContextProvider>
      </body>
      
      
    </html>
  );
}
